# Generated by Django 2.2.6 on 2019-10-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
